### ISSUE TITLE
有没有办法下载高清的

### ISSUE THREAD

**Issue by Fs865** [qinlili23333/nlcDownloader#2]
现在虽然可以下载PDF了，但是都是模糊的图片，看不清字
![QQ截图20230201095826](https://user-images.githubusercontent.com/102808020/215926412-1fe34ca1-24d5-453f-b231-7bf084cc7288.jpg)

**Comment by qinlili23333** [comment]
pdf均为原始文件，看不清那就是源文件就不清晰

**Comment by Fs865** [comment]
emmm 但是在线看的时候放大，就会特别的清晰，不晓得是不是换了源文件了。
![QQ截图20230201110338](https://user-images.githubusercontent.com/102808020/215935037-ad60dfa1-6fa0-4030-b816-d8c32ec94d87.jpg)

**Comment by qinlili23333** [comment]
理论上下载的就是源文件

**Comment by Fs865** [comment]
好的，谢谢大佬，我没问题啦。
